name: walmonitor
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pandas=3.0.0
  - shiny=1.4.0
  - altair-all=5.4.*
  - nb_conda_kernels=2.5.1 
  - pip=26.0.1
  - pip:
    - altair_ally==0.1.1 
